package Admin;



import Customer.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/**
 *
 * @author Kristine
 */
public class Store extends javax.swing.JFrame {

    /**
     * Creates new form Store1
     */
    public Store() {
        initComponents();
        DisplayItems();
        nonactive();
    }

    public void nonactive() {
   
        sbar.setVisible(false);
        sbar.setEnabled(false);

        menu.setVisible(true);
        menu.setEnabled(true);
        
   }

    public void active() {

        sbar.setVisible(true);
        sbar.setEnabled(true);

        menu.setVisible(false);
        menu.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        sbar = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JButton();
        CustomerManagementButton = new javax.swing.JButton();
        ProductsButton = new javax.swing.JButton();
        ViewOrdersBtn = new javax.swing.JButton();
        SalesRecordButton = new javax.swing.JButton();
        HelpAndSupportButton = new javax.swing.JButton();
        StockButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LogoutBtn1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        cart1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        WheelsAndTiresBtn = new javax.swing.JButton();
        AccessoriesBtn = new javax.swing.JButton();
        HornsBtn = new javax.swing.JButton();
        FluidsAndLubricantsBtn = new javax.swing.JButton();
        EngineComponentsBtn = new javax.swing.JButton();
        CustomerBtn = new javax.swing.JButton();
        desktopPanel = new javax.swing.JDesktopPane();
        menu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductsTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sbar.setBackground(new java.awt.Color(102, 102, 102));

        DashboardButton.setBackground(new java.awt.Color(204, 153, 0));
        DashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        DashboardButton.setText("Dashboard");
        DashboardButton.setBorderPainted(false);
        DashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });

        CustomerManagementButton.setBackground(new java.awt.Color(102, 102, 102));
        CustomerManagementButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CustomerManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomerManagementButton.setText("Customers");
        CustomerManagementButton.setBorderPainted(false);
        CustomerManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerManagementButtonActionPerformed(evt);
            }
        });

        ProductsButton.setBackground(new java.awt.Color(102, 102, 102));
        ProductsButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ProductsButton.setForeground(new java.awt.Color(255, 255, 255));
        ProductsButton.setText("Manage Products");
        ProductsButton.setBorderPainted(false);
        ProductsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsButtonActionPerformed(evt);
            }
        });

        ViewOrdersBtn.setBackground(new java.awt.Color(102, 102, 102));
        ViewOrdersBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ViewOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewOrdersBtn.setText("View Orders");
        ViewOrdersBtn.setBorderPainted(false);
        ViewOrdersBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrdersBtnActionPerformed(evt);
            }
        });

        SalesRecordButton.setBackground(new java.awt.Color(102, 102, 102));
        SalesRecordButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SalesRecordButton.setForeground(new java.awt.Color(255, 255, 255));
        SalesRecordButton.setText("Sales Record");
        SalesRecordButton.setBorderPainted(false);
        SalesRecordButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SalesRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesRecordButtonActionPerformed(evt);
            }
        });

        HelpAndSupportButton.setBackground(new java.awt.Color(102, 102, 102));
        HelpAndSupportButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HelpAndSupportButton.setForeground(new java.awt.Color(255, 255, 255));
        HelpAndSupportButton.setText("About Us");
        HelpAndSupportButton.setBorderPainted(false);
        HelpAndSupportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HelpAndSupportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpAndSupportButtonActionPerformed(evt);
            }
        });

        StockButton.setBackground(new java.awt.Color(102, 102, 102));
        StockButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        StockButton.setForeground(new java.awt.Color(255, 255, 255));
        StockButton.setText("View Stocks");
        StockButton.setBorderPainted(false);
        StockButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockButtonActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/inventory.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sales.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ordermanagement.png"))); // NOI18N
        jLabel14.setText("jLabel7");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/products.png"))); // NOI18N
        jLabel15.setText("jLabel9");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/information.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard.png"))); // NOI18N

        LogoutBtn1.setBackground(new java.awt.Color(204, 204, 204));
        LogoutBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBtn1.setForeground(new java.awt.Color(51, 51, 51));
        LogoutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        LogoutBtn1.setText("Logout");
        LogoutBtn1.setBorderPainted(false);
        LogoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtn1ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/admin.png"))); // NOI18N

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ADMIN");

        menu1.setBackground(new java.awt.Color(102, 102, 102));
        menu1.setForeground(new java.awt.Color(153, 126, 21));
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next (1).png"))); // NOI18N
        menu1.setBorder(null);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sbarLayout = new javax.swing.GroupLayout(sbar);
        sbar.setLayout(sbarLayout);
        sbarLayout.setHorizontalGroup(
            sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sbarLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sbarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sbarLayout.createSequentialGroup()
                                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sbarLayout.createSequentialGroup()
                                        .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CustomerManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StockButton)
                                            .addComponent(SalesRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ViewOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ProductsButton))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sbarLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(HelpAndSupportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(sbarLayout.createSequentialGroup()
                                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sbarLayout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(sbarLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(LogoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(sbarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(menu1)
                .addContainerGap())
        );
        sbarLayout.setVerticalGroup(
            sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(14, 14, 14)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalesRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StockButton))
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sbarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sbarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HelpAndSupportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(sbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sbarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel17))
                    .addGroup(sbarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LogoutBtn1)))
                .addContainerGap(615, Short.MAX_VALUE))
        );

        jPanel7.add(sbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("All Products");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("All Categories");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        cart.setBackground(new java.awt.Color(223, 169, 4));
        cart.setForeground(new java.awt.Color(255, 204, 0));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/information.png"))); // NOI18N
        cart.setBorderPainted(false);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel7.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, -1, 40));

        cart1.setBackground(new java.awt.Color(223, 169, 4));
        cart1.setForeground(new java.awt.Color(255, 204, 0));
        cart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cart.png"))); // NOI18N
        cart1.setBorderPainted(false);
        cart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cart1ActionPerformed(evt);
            }
        });
        jPanel7.add(cart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Wheels and Tires");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Fluids and Lubricants");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Engine Components");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Accessories");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Horns");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        WheelsAndTiresBtn.setBackground(new java.awt.Color(255, 255, 255));
        WheelsAndTiresBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.5.png"))); // NOI18N
        WheelsAndTiresBtn.setText("jButton2");
        WheelsAndTiresBtn.setBorder(null);
        WheelsAndTiresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelsAndTiresBtnActionPerformed(evt);
            }
        });
        jPanel7.add(WheelsAndTiresBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 170, 180));

        AccessoriesBtn.setBackground(new java.awt.Color(255, 255, 255));
        AccessoriesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.1.png"))); // NOI18N
        AccessoriesBtn.setText("jButton2");
        AccessoriesBtn.setBorder(null);
        AccessoriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesBtnActionPerformed(evt);
            }
        });
        jPanel7.add(AccessoriesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 170, 180));

        HornsBtn.setBackground(new java.awt.Color(255, 255, 255));
        HornsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.2.png"))); // NOI18N
        HornsBtn.setText("jButton2");
        HornsBtn.setBorder(null);
        HornsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HornsBtnActionPerformed(evt);
            }
        });
        jPanel7.add(HornsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 170, 180));

        FluidsAndLubricantsBtn.setBackground(new java.awt.Color(255, 255, 255));
        FluidsAndLubricantsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.3.png"))); // NOI18N
        FluidsAndLubricantsBtn.setText("jButton2");
        FluidsAndLubricantsBtn.setBorder(null);
        FluidsAndLubricantsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FluidsAndLubricantsBtnActionPerformed(evt);
            }
        });
        jPanel7.add(FluidsAndLubricantsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 170, 180));

        EngineComponentsBtn.setBackground(new java.awt.Color(255, 255, 255));
        EngineComponentsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.4.png"))); // NOI18N
        EngineComponentsBtn.setText("jButton2");
        EngineComponentsBtn.setBorder(null);
        EngineComponentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineComponentsBtnActionPerformed(evt);
            }
        });
        jPanel7.add(EngineComponentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 180));

        CustomerBtn.setBackground(new java.awt.Color(210, 161, 12));
        CustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomerBtn.setForeground(new java.awt.Color(51, 51, 51));
        CustomerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        CustomerBtn.setText("back to main menu");
        CustomerBtn.setBorderPainted(false);
        CustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerBtnActionPerformed(evt);
            }
        });
        jPanel7.add(CustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, -1));

        desktopPanel.setBackground(new java.awt.Color(204, 153, 0));

        menu.setBackground(new java.awt.Color(201, 163, 9));
        menu.setForeground(new java.awt.Color(153, 126, 21));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/burger-bar.png"))); // NOI18N
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        desktopPanel.setLayer(menu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPanelLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(menu))
        );

        jPanel7.add(desktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 40));
        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-38, 400, 30, 150));

        ProductsTable.setBackground(new java.awt.Color(204, 204, 204));
        ProductsTable.setForeground(new java.awt.Color(0, 0, 0));
        ProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ProductID", "Name", "Stocks", "Price", "Category", "Description"
            }
        ));
        ProductsTable.setSelectionBackground(new java.awt.Color(51, 51, 51));
        ProductsTable.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(ProductsTable);

        jScrollPane4.setViewportView(jScrollPane2);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 970, 210));

        searchField.setBackground(new java.awt.Color(204, 204, 204));
        searchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(102, 102, 102));
        searchField.setText("   Search...");
        searchField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        searchField.setSelectionColor(new java.awt.Color(102, 102, 102));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel7.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 419, 30));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/searchbar.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel7.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartActionPerformed

    private void cart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cart1ActionPerformed

    private void WheelsAndTiresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelsAndTiresBtnActionPerformed
        // TODO add your handling code here:
        WheelsAndTiresShop  wheelsandtiresshop = new WheelsAndTiresShop();
        wheelsandtiresshop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WheelsAndTiresBtnActionPerformed

    private void AccessoriesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesBtnActionPerformed
        // TODO add your handling code here:
        AccessoriesShop accessoriesshop = new AccessoriesShop();
        accessoriesshop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccessoriesBtnActionPerformed

    private void HornsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HornsBtnActionPerformed
        // TODO add your handling code here:
        HornsShop hornsshop = new HornsShop();
        hornsshop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HornsBtnActionPerformed

    private void FluidsAndLubricantsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FluidsAndLubricantsBtnActionPerformed
        // TODO add your handling code here:
        FluidsLubricantsShop fluidslubricantsshop = new FluidsLubricantsShop();
        fluidslubricantsshop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FluidsAndLubricantsBtnActionPerformed

    private void EngineComponentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineComponentsBtnActionPerformed
        // TODO add your handling code here:
        EngineComponentsShop enginecomponentsshop = new EngineComponentsShop();
        enginecomponentsshop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EngineComponentsBtnActionPerformed

    private void CustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerBtnActionPerformed
        // TODO add your handling code here:
        CustomerDashboard customerdashboard = new CustomerDashboard();
        customerdashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CustomerBtnActionPerformed
    
    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed

    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String searchQuery = searchField.getText().trim();
        if (searchQuery.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search term.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Establish a connection to the database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autopartssales_db", "root", "your_password");

            // SQL query to search for items
            String sql = "SELECT * FROM products WHERE ProductName LIKE ? OR Category LIKE ? OR Brand LIKE ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + searchQuery + "%");
            pst.setString(2, "%" + searchQuery + "%");
            pst.setString(3, "%" + searchQuery + "%");

            // Execute the query
            ResultSet rs = pst.executeQuery();

            // Get the table model
            DefaultTableModel model = (DefaultTableModel) ProductsTable.getModel();
            model.setRowCount(0); // Clear existing rows in the table

            // Populate the table with the search results
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ProductID"),
                    rs.getString("ProductName"),
                    rs.getString("Category"),
                    rs.getDouble("Price"),
                    rs.getInt("Stock"),
                    rs.getString("Description"),
                    rs.getString("Brand")
                });
            }

            // Close connections
            rs.close();
            pst.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error while searching: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        active();
    }//GEN-LAST:event_menuActionPerformed

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
        // TODO add your handling code here:
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void CustomerManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerManagementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerManagementButtonActionPerformed

    private void ProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsButtonActionPerformed
        // TODO add your handling code here:
        ManageProduct manageproduct = new ManageProduct();
        manageproduct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsButtonActionPerformed

    private void ViewOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrdersBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewOrdersBtnActionPerformed

    private void SalesRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesRecordButtonActionPerformed
        // TODO add your handling code here:
        SalesRecord salesRecord = new SalesRecord();
        salesRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalesRecordButtonActionPerformed

    private void HelpAndSupportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpAndSupportButtonActionPerformed
        // TODO add your handling code here:
        AboutUS aboutus = new AboutUS();
        aboutus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HelpAndSupportButtonActionPerformed

    private void StockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockButtonActionPerformed
        // TODO add your handling code here:
        Stocks stocks = new Stocks();
        stocks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StockButtonActionPerformed

    private void LogoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtn1ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            // Terminate the application
            System.exit(0);
        }
    }//GEN-LAST:event_LogoutBtn1ActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        Store store = new Store();
        store.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void DisplayItems(){

        try {
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/autopartssales_db", "root", "your_password");
            Statement St = Con.createStatement();
            ResultSet Rs = St.executeQuery("SELECT ProductID, ProductName, Brand, Price, Stock, Description, Category FROM products");
            ProductsTable.setModel(DbUtils.resultSetToTableModel(Rs));  // Make sure the table is updated correctly
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error displaying items: " + e.getMessage());
        }
     }
    
    
    
    
    
  public static void main(String[] args) {
    // Set the look and feel to the system default (optional)
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    // Launch the frame
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Store().setVisible(true); 
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccessoriesBtn;
    private javax.swing.JButton CustomerBtn;
    private javax.swing.JButton CustomerManagementButton;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JButton EngineComponentsBtn;
    private javax.swing.JButton FluidsAndLubricantsBtn;
    private javax.swing.JButton HelpAndSupportButton;
    private javax.swing.JButton HornsBtn;
    private javax.swing.JButton LogoutBtn1;
    private javax.swing.JButton ProductsButton;
    private javax.swing.JTable ProductsTable;
    private javax.swing.JButton SalesRecordButton;
    private javax.swing.JButton StockButton;
    private javax.swing.JButton ViewOrdersBtn;
    private javax.swing.JButton WheelsAndTiresBtn;
    private javax.swing.JButton cart;
    private javax.swing.JButton cart1;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu1;
    private javax.swing.JPanel sbar;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

}

